#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# DevPilot Identity Server – install script (macOS / Linux)
#
# Usage:
#   ./install.sh                       # generate certs + start
#   ./install.sh --no-certs            # skip cert generation (use existing)
#   ./install.sh --trust-cert          # also trust cert in OS store (macOS)
#   ./install.sh --username admin      # override admin username
#   ./install.sh --port 5001           # override IDS port
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Defaults ─────────────────────────────────────────────────────────────────
GENERATE_CERTS=true
TRUST_CERT=false
IDS_PORT=5001
ADMIN_USERNAME="ibenamara"
ADMIN_EMAIL=""
ADMIN_DISPLAY_NAME=""
CERT_PASSWORD="devpassword"

# ── Parse arguments ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-certs)      GENERATE_CERTS=false; shift ;;
    --trust-cert)    TRUST_CERT=true; shift ;;
    --port)          IDS_PORT="$2"; shift 2 ;;
    --username)      ADMIN_USERNAME="$2"; shift 2 ;;
    --email)         ADMIN_EMAIL="$2"; shift 2 ;;
    --display-name)  ADMIN_DISPLAY_NAME="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --no-certs       Skip certificate generation (reuse existing certs/)"
      echo "  --trust-cert     Trust the certificate in the OS store (macOS only)"
      echo "  --port PORT      Identity server port (default: 5001)"
      echo "  --username NAME  Admin username (default: ibenamara)"
      echo "  --email EMAIL    Admin email"
      echo "  --display-name N Admin display name"
      echo "  -h, --help       Show this help"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Derived defaults ─────────────────────────────────────────────────────────
ADMIN_EMAIL="${ADMIN_EMAIL:-${ADMIN_USERNAME}@devpilot.local}"
ADMIN_DISPLAY_NAME="${ADMIN_DISPLAY_NAME:-${ADMIN_USERNAME}}"

# ── Check dependencies ───────────────────────────────────────────────────────
echo "==> Checking dependencies..."
for cmd in docker openssl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is required but not found. Please install it first."
    exit 1
  fi
done

if ! docker info &>/dev/null; then
  echo "ERROR: Docker is not running. Please start Docker Desktop first."
  exit 1
fi

echo "    docker  ✓"
echo "    openssl ✓"

# ── Generate admin password ──────────────────────────────────────────────────
ADMIN_PASSWORD="$(openssl rand -base64 16 | tr -d '/+=' | head -c 16)Dp1!"
echo ""
echo "==> Admin credentials"
echo "    Username : $ADMIN_USERNAME"
echo "    Password : $ADMIN_PASSWORD"
echo "    Email    : $ADMIN_EMAIL"

# ── Generate certificates ────────────────────────────────────────────────────
if [ "$GENERATE_CERTS" = true ]; then
  echo ""
  echo "==> Generating self-signed certificates..."
  mkdir -p certs

  openssl req -x509 -newkey rsa:2048 \
    -keyout certs/localhost.key \
    -out certs/localhost.crt \
    -days 365 -nodes \
    -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
    2>/dev/null

  # Generate PFX with legacy algorithms for .NET container compatibility
  openssl pkcs12 -export \
    -out certs/localhost.pfx \
    -inkey certs/localhost.key \
    -in certs/localhost.crt \
    -passout "pass:${CERT_PASSWORD}" \
    -certpbe PBE-SHA1-3DES -keypbe PBE-SHA1-3DES -macalg sha1 \
    2>/dev/null

  echo "    certs/localhost.crt ✓"
  echo "    certs/localhost.pfx ✓"
else
  if [ ! -f certs/localhost.pfx ]; then
    echo "ERROR: certs/localhost.pfx not found. Remove --no-certs to generate."
    exit 1
  fi
  echo ""
  echo "==> Using existing certificates in certs/"
fi

# ── Trust certificate (macOS only) ──────────────────────────────────────────
if [ "$TRUST_CERT" = true ]; then
  if [[ "$(uname)" == "Darwin" ]]; then
    echo ""
    echo "==> Trusting certificate in macOS Keychain (requires sudo)..."
    sudo security add-trusted-cert -d -r trustRoot \
      -k /Library/Keychains/System.keychain \
      certs/localhost.crt
    echo "    Certificate trusted ✓"
  else
    echo ""
    echo "==> Trusting certificate in system CA store..."
    sudo cp certs/localhost.crt /usr/local/share/ca-certificates/devpilot-localhost.crt
    sudo update-ca-certificates 2>/dev/null
    echo "    Certificate trusted ✓"
  fi
fi

# ── Write .env file ─────────────────────────────────────────────────────────
echo ""
echo "==> Writing .env file..."
cat > .env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
IDS_PORT=${IDS_PORT}
CERT_PASSWORD=${CERT_PASSWORD}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_DISPLAY_NAME=${ADMIN_DISPLAY_NAME}
REDIS_PORT=6379
EOF
echo "    .env ✓"

# ── Update blazor-appsettings.json with the correct port ────────────────────
echo ""
echo "==> Updating blazor-appsettings.json for port ${IDS_PORT}..."
python3 -c "
import json
with open('blazor-appsettings.json', 'r') as f:
    d = json.load(f)
port = '${IDS_PORT}'
base = f'https://localhost:{port}'
d['apiBaseUrl'] = f'{base}/api'
d['providerOptions']['authority'] = f'{base}/'
d['providerOptions']['redirectUri'] = f'{base}/authentication/login-callback'
d['providerOptions']['postLogoutRedirectUri'] = f'{base}/authentication/logout-callback'
d['settingsOptions']['apiUrl'] = f'{base}/api/api/configuration'
with open('blazor-appsettings.json', 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
" 2>/dev/null || echo "    (python3 not available – blazor-appsettings.json uses default port 5001)"
echo "    blazor-appsettings.json ✓"

# ── Stop any existing containers ─────────────────────────────────────────────
echo ""
echo "==> Starting containers..."
docker compose down --remove-orphans -v 2>/dev/null || true
docker compose up -d

# ── Wait for health ──────────────────────────────────────────────────────────
echo ""
echo "==> Waiting for Identity Server to be ready..."
MAX_WAIT=60
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
  if curl -sk -o /dev/null -w "%{http_code}" "https://localhost:${IDS_PORT}/.well-known/openid-configuration" 2>/dev/null | grep -q "200"; then
    break
  fi
  sleep 2
  ELAPSED=$((ELAPSED + 2))
done

if [ $ELAPSED -ge $MAX_WAIT ]; then
  echo "    WARNING: Server did not become ready within ${MAX_WAIT}s."
  echo "    Check logs: docker logs devpilot-duende"
else
  echo "    Identity Server is ready ✓"
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════════════"
echo "  DevPilot Identity Server is running!"
echo ""
echo "  Admin UI       : https://localhost:${IDS_PORT}"
echo "  OIDC Discovery : https://localhost:${IDS_PORT}/.well-known/openid-configuration"
echo ""
echo "  Admin login"
echo "    Username : ${ADMIN_USERNAME}"
echo "    Password : ${ADMIN_PASSWORD}"
echo ""
echo "  OIDC Client ID : devpilot-spa"
echo ""
if [ "$TRUST_CERT" = false ]; then
  echo "  NOTE: The self-signed certificate is NOT trusted by your OS."
  echo "  Your browser will show a warning. To trust it, re-run with:"
  echo "    ./install.sh --no-certs --trust-cert"
  echo ""
fi
echo "══════════════════════════════════════════════════════════════════"
