#!/usr/bin/env bash
# Build devpilot-desktop (Dockerfile generated by infra/sandbox/setup.sh) and push to a registry.
#
# If you build with plain "docker build" on Apple Silicon, the image is often linux/arm64 only.
# Servers / CI usually need linux/amd64 → use --buildx so the registry gets the right architecture
# (or multi-arch so both Mac and server work).
#
# Usage:
#   ./infra/sandbox/build-push-desktop.sh [--build] [--buildx] [--platform=LIST] <image:tag>
#
#   --build     Run BUILD_ONLY=1 setup.sh first (generates /opt/devpilot-sandbox/desktop)
#   --buildx    Use docker buildx and --push (no local single-arch tag). Required for amd64 from ARM Mac.
#   --platform= Comma-separated platforms (default with --buildx: linux/amd64,linux/arm64)
#               Example for Linux servers only: --platform=linux/amd64
#
# Examples:
#   ./infra/sandbox/build-push-desktop.sh --build --buildx issambenamara/devpilot-desktop:latest
#   ./infra/sandbox/build-push-desktop.sh --build --buildx --platform=linux/amd64 issambenamara/devpilot-desktop:latest
#
# Push-only (image already local — same architecture only):
#   ./infra/sandbox/build-push-desktop.sh issambenamara/devpilot-desktop:latest
#
# Prerequisites:
#   - docker login
#   - Writable /opt/devpilot-sandbox for --build (or: sudo mkdir -p /opt/devpilot-sandbox && sudo chown "$(whoami)" /opt/devpilot-sandbox)
#   - For --buildx: Docker Buildx available (Docker Desktop includes it)
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DO_BUILD=false
USE_BUILDX=false
PLATFORMS="linux/amd64,linux/arm64"
TARGET=""
DESKTOP_DIR="${DESKTOP_DIR:-/opt/devpilot-sandbox/desktop}"

while [ $# -gt 0 ]; do
  case "$1" in
    --build)   DO_BUILD=true ;;
    --buildx)  USE_BUILDX=true ;;
    --platform=*)
      PLATFORMS="${1#*=}"
      USE_BUILDX=true
      ;;
    *)
      if [ -n "${TARGET:-}" ]; then
        echo "ERROR: Unexpected extra argument: $1"
        exit 1
      fi
      TARGET="$1"
      ;;
  esac
  shift
done

if [ -z "${TARGET:-}" ]; then
  echo "Usage: $0 [--build] [--buildx] [--platform=linux/amd64,...] <registry/image:tag>"
  echo "  Multi-arch (recommended): $0 --build --buildx YOUR_USER/devpilot-desktop:latest"
  echo "  AMD64 only (Linux servers): $0 --build --buildx --platform=linux/amd64 YOUR_USER/devpilot-desktop:latest"
  exit 1
fi

if [ "$DO_BUILD" = true ]; then
  echo "==> BUILD_ONLY=1 infra/sandbox/setup.sh (10–20 min first time)..."
  export BUILD_ONLY=1
  bash "$REPO_ROOT/infra/sandbox/setup.sh"
fi

if [ "$USE_BUILDX" = true ]; then
  if [ ! -f "$DESKTOP_DIR/Dockerfile" ]; then
    echo "ERROR: No Dockerfile at $DESKTOP_DIR — run with --build first (or set DESKTOP_DIR)."
    exit 1
  fi
  echo "==> buildx build --platform $PLATFORMS -> $TARGET (push)"
  # Multi-arch --push needs a buildx builder (docker-container driver can build amd64 on ARM Mac via QEMU).
  BUILDER="devpilot-desktop-buildx"
  if ! docker buildx inspect "$BUILDER" &>/dev/null; then
    docker buildx create --name "$BUILDER" --driver docker-container --bootstrap --use
  else
    docker buildx use "$BUILDER"
  fi
  docker buildx build \
    --platform "$PLATFORMS" \
    -t "$TARGET" \
    --push \
    "$DESKTOP_DIR"
  echo "Done. Set in .env: SANDBOX_IMAGE=$TARGET"
  exit 0
fi

if ! docker image inspect devpilot-desktop:latest &>/dev/null; then
  echo "ERROR: Local image devpilot-desktop:latest not found. Run with --build first."
  exit 1
fi

echo "==> Tag devpilot-desktop:latest -> $TARGET"
docker tag devpilot-desktop:latest "$TARGET"

echo "==> Push $TARGET"
docker push "$TARGET"
echo "NOTE: This push is single-architecture (often arm64 on Apple Silicon). Linux amd64 hosts may need:"
echo "      $0 --build --buildx --platform=linux/amd64 $TARGET"
echo "Done. Set in .env: SANDBOX_IMAGE=$TARGET"
